apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        image: dangtong/hostservice:299f414c194eb6bf5e9793fef351b385509f588e
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080